### ISSUE TITLE
bug: TODO and HACK behave differently than all other keywords when highlight.keyword = "fg"

### ISSUE THREAD

**Issue by brandonjtnoguera** [folke/todo-comments.nvim#189]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

 MacOS Ventura 13.2.1

### Describe the bug

`"HACK"` and `"TODO"` still have a yellow block around them when setting `highlight.keyword = "fg"`
<img width="754" alt="image" src="https://user-images.githubusercontent.com/58859142/225686051-f44dd4c5-a5b3-42bb-a11c-18b10e6f26c7.png">

### Steps To Reproduce

1. Install `todo-comments.nvim`
2. 
```lua
require("todo-comments").setup({
      keywords = {
        FIX = {
          icon = " ", -- icon used for the sign, and in search results
          color = "error", -- can be a hex color, or a named color (see below)
          alt = { "FIXME", "BUG", "FIXIT", "ISSUE" }, -- a set of other keywords that all map to this FIX keywords
          -- signs = false, -- configure signs for some keywords individually
        },
        TODO = { icon = " ", color = "info" },
        HACK = { icon = " ", color = "warning" },
        WARN = { icon = " ", color = "warning", alt = { "WARNING", "XXX" } },
        PERF = { icon = " ", alt = { "OPTIM", "PERFORMANCE", "OPTIMIZE" } },
        NOTE = { icon = " ", color = "hint", alt = { "INFO" } },
        TEST = { icon = "⏲ ", color = "test", alt = { "TESTING", "PASSED", "FAILED" } },
      },

      gui_style = {
        fg = "NONE",
        bg = "BOLD"
      },

      highlight = {
        -- TODO hi
        -- HACK
        -- PERF
        -- FIX
        -- WARN
        -- NOTE
        before = "fg", -- "fg" or "bg" or empty
        keyword = "fg", -- "fg", "bg", "wide", "wide_bg", "wide_fg" or empty. (wide and wide_bg is the same as bg, but will also highlight surrounding characters, wide_fg acts accordingly but with fg)
        after = "fg", -- "fg" or "bg" or empty
        pattern = [[.*<(KEYWORDS)\s*]], -- pattern or table of patterns, used for highlightng (vim regex)
      }
    })
```
3. `TODO` and `HACK` will have a yellow block around them, but the rest of the keywords will not.

### Expected Behavior

I expected `TODO` and `HACK` to be highlighted like `FIX`, `PERF`, `NOTE`, and `WARN` are in the screenshot

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/todo-comments.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
you probably have the treesitter comments parser installed? Uninstall it if you dont want that highlighting.
