### ISSUE TITLE
bug: NvChad with Todo-Comments set the buftype to nofile when opening a file

### ISSUE THREAD

**Issue by fabiodcorreia** [folke/todo-comments.nvim#215]
### Did you check docs and existing issues?

- [X] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOs 13.4.1

### Describe the bug

Whe the plugins is installed if I open a file with `nvim filename.txt` and try to save it I get the error `cannot write 'buftype' option is set` and after checking I see the buftype is set to nofile.

If I disable the plugin and repeat the steps it works fine.

### Steps To Reproduce

1. Open a file directly with `nvim filename.txt`
2. Try do save it with `:w`

### Expected Behavior

The buftype should be set correctly, not to nofile and allow to write.

**Comment by fabiodcorreia** [comment]
I found this happens if I set the ft="*" on Lazy. If I remove that and put lazy=true it works fine.
If I don't use the lazy=true like the example provided it doesn't load.
