### ISSUE TITLE
question: "todo-comments isn't loaded. Did you run setup()?" How do I run setup()?

### ISSUE THREAD

**Issue by RhysFonville** [folke/todo-comments.nvim#238]
### Did you check docs and existing issues?

- [x] I have read all the todo-comments.nvim docs
- [X] I have searched the existing issues of todo-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-1438+g8405649f9

### Operating system/version

5.10.0-26-amd64

### Describe the bug

I installed the plugin through Vundle, and when using the plugin (Running `:TodoQuickFix`), it tells me "todo-comments isn't loaded. Did you run setup()?"

### Steps To Reproduce

1. Install the plugin through Vundle. Write in your .vimrc `Plugin 'folke/todo-comments.nvim`
2. Save your .vimrc and run `:PluginInstall`
3. Run `:TodoQuickFix`

### Expected Behavior

The plugin should execute the `:TodoQuickFix` properly. I'm not sure how to run setup().

**Comment by robsonandradev** [comment]
UP

**Comment by RhysFonville** [comment]
Hm?

**Comment by rlpowell** [comment]
Add `require("todo-comments").setup()` to your lua config, is what worked for me.

**Comment by devpaps** [comment]
Im using lazy.nvim and this is my setup:
` 	{
		"folke/todo-comments.nvim",
		dependencies = { "nvim-lua/plenary.nvim" },
		opts = {
			vim.keymap.set("n", "<leader>lt", "<cmd>TodoQuickFix<cr>", { noremap = true, silent = true }),
		},
	},
`

It works for me.

**Comment by RhysFonville** [comment]
I don't use lazy.nvim, but @rlpowell's example seems to work. Thanks guys.
